import type {Metadata} from "next";
import "./globals.css";
import {nunitoSans} from "@/app/fonts";
import {ReactQueryProvider} from "@/app/ReactQueryProvider";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ReactQueryProvider>
            <html lang="en">
            <body className={nunitoSans.className}>{children}</body>
            </html>
        </ReactQueryProvider>
    );
}
